Сетка страниц и крупных блоков на флексах
htmlacademy-htmlcss/2368577-sedona-1 pull request #5
Opened 2023-10-18 08:01 UTC by PolinaGoltsova

Малик, привет. что-то очень тяжело пошла тема сетки. Я задавала вопросы в самих файлас с помощью коментариев. Наверное потом нужна будет голосовая консультация.

2023-10-18 10:28 UTC, DoberBober commented on index.html
> +    <!-- есть ли разница, добавляю я новый класс перед или после уже заданного? мне нужно добавить main-container. Есть ли отличия между: <main class=" main-container main-index"> и <main class="main
Разницы нет. Важно в каком порядке идут эти классы в CSS.

2023-10-18 10:29 UTC, DoberBober commented on styles/styles.css
> +/* почему мы задаем display: flex; сразу на body, а не отдельным тегам, например header, main и тд?   */
Скорее всего, это чтобы прижать футер к низу страницы, если сама страница короткая. Вероятно, флекс у тебя заменитсы на грид через пару заданий.

2023-10-18 10:31 UTC, DoberBober commented on styles/styles.css
> +  /* не понимаю, зачем мы добавили: min-height: 100%; Что это дает?  */
Если страница короткая, то футер может оказаться наверху (как на скрине). Это нежелательное поведение. Поэтому ты растягиваешь body как минимум на высоту экрана. Для body задаешь флекс. И для main надо ещё дописать `flex-grow: 1`.
![image](https://github.com/htmlacademy-htmlcss/2368577-sedona-1/assets/18398812/79384e32-a528-43a1-b158-58ad0a07542a)

В итоге футер будет оставаться всегда внизу.
![image](https://github.com/htmlacademy-htmlcss/2368577-sedona-1/assets/18398812/d9204bcc-33de-4cb0-86c1-a311ef798d8d)

2023-10-18 10:32 UTC, DoberBober commented on styles/styles.css
> +  align-content: stretch; - почему с помощью этих правил не получается расположить блоки в 3 ряда? */
flex-direction убери.)

2023-10-18 10:33 UTC, DoberBober commented on styles/styles.css
> +/* у меня не получилось расположить компоненты по краям футера, почему они сгруппировались в центре? */
У тебя сейчас всё содержимое футера лежит внутри `footer-social`. Закрой его перед `footer-telefon-number-container`. Должно получиться после этого.

2023-10-18 10:34 UTC, DoberBober commented on styles/styles.css
> +/* почему компоненты ниже не встают в линию, хотя я задаю значение flex-direction: row; ?  */
Для `catalog-filter` задай флекс.

2023-10-18 10:35 UTC, DoberBober requested changes
Пока сыро, надо доработать.
И пропиши ссылки на страницы в меню, пожалуйста, чтобы можно было переключаться кликом.

2023-10-22 12:05 UTC, PolinaGoltsova commented
Малик, привет! исправила сетку + добавила в код несколько вопросов.

2023-10-22 12:43 UTC, DoberBober commented on styles/styles.css
> +/* как сделать так, чтобы все кнопки пагинации были квадратные? сейчас у них разные паддинги в зависимости от числа. Или нужно каждой кнопке задавать паддинг? */
Тупо размер задай, с небольшим паддингом. А центровку текста сделай через флекс.

2023-10-22 12:44 UTC, DoberBober commented on styles/styles.css
> +/* почему иконка домика в хлебных крошках черная, хотя задан белый цвет? Почему она не встает по центру (для breadcrumps я указала text-align - center)?*/
Так как свгшка выведена фоном, то ты цвет никак не можешь поменять. Только открыть саму свгшку в редакторе и поправить её цвет.

2023-10-22 12:44 UTC, DoberBober commented on styles/styles.css
> +/* как расположить иконки в центре? */
`background-position center`.

2023-10-22 12:44 UTC, DoberBober approved these changes
Огонь!

2023-10-22 12:44 UTC, merged